baseURL = "https://toshi52kan.github.io/"
publishDir = "docs"
languageCode = "ja"
title = "My New Hugo Site"
theme = "hugo-tikva"
[menu]
    [[menu.main]]
        identifier = ""
        name = "Home"
        url = "/"
        weight = 1
    [[menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/public/post"
        weight = 2
    [[menu.main]]
        identifier = "flutter"
        name = "Flutter"
        url = "/flutter/start/about/"
        weight = 3
